name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NFT Contract Build & Test
        run: |
          cd contracts/nft_contract
          cargo build --release
          cargo test --target x86_64-unknown-linux-gnu

      - name: Metadata Contract Build & Test
        run: |
          cd contracts/metadata_contract
          cargo build --release
          cargo test --target x86_64-unknown-linux-gnu

      - name: Token Contract Build & Test
        run: |
          cd contracts/fungible_contract
          cargo build --release
          cargo test --target x86_64-unknown-linux-gnu

      - name: Frontend Build & Test
        run: |
          cd frontend
          npm install
          npm run build
          npm run test -- --run
